dataset_name: MCO
slide_root_dir: ${oc.env:MCO_ROOT_DIR}
patch_dir: ${oc.env:SLIDE_PROCESS_DIR}/MCO-SCalib/patches_512
feat_base_dir: ${oc.env:SLIDE_PROCESS_DIR}/MCO-SCalib
patch_size: 512
extensions: [".svs"]
resize_val: 256
crop_val: 224
batch_size: 256
num_workers: 8
model: resnet18
backend: cucim
pbar_refresh_rate: 0