name: mco-gnn-ciga
save_dir: ${oc.env:EXPERIMENT_LOCATION}/slide-calib_512
eval: true
seed_everything: 42
data:
  class_path: src.datamodules.HistoSlideModule
  init_args:
    data_p: ${oc.env:SLIDE_PROCESS_DIR}/MCO-SCalib
    feature_folder: features_512_resnet18-ciga
    patch_folder: patches_512
    task: msi
    batch_size: 1
    num_workers: 8
    fold: 1
    data_ood_p: ${oc.env:SLIDE_PROCESS_DIR}/TCGA-CRC-SCalib
model:
  class_path: src.pl_modules.GraphLevelGNN
  init_args:
    input_dim: 512
    c_in: 256
    c_hidden: 512
    c_out: 2
    layer_name: GAT
    num_layers: 3
    dp_in: 0.1
    dp_model: 0.1
    dp_out: 0.1
    lr: 2e-3
    weight_decay: 0.0    
trainer:
  callbacks:
    - class_path: pytorch_lightning.callbacks.TQDMProgressBar
      init_args:
        refresh_rate: 200
  accelerator: gpu
  devices: 1
  strategy: null
  precision: 16
  num_sanity_val_steps: 0
  limit_val_batches: 1.0
  accumulate_grad_batches: 32
  max_epochs: 200
